# Generated by Django 6.1 on 2026-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="craft",
            name="making_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
