# Generated by Django 6.1 on 2026-09-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_craft_making_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("cultural_context", models.TextField(blank=True)),
                ("region", models.CharField(blank=True, max_length=150)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="practices/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="artisan",
            name="practices",
            field=models.ManyToManyField(
                blank=True, related_name="artisans", to="marketplace.practice"
            ),
        ),
        migrations.AddField(
            model_name="craft",
            name="practices",
            field=models.ManyToManyField(
                blank=True, related_name="crafts", to="marketplace.practice"
            ),
        ),
    ]
