# Generated by Django 6.1 on 2026-09-12 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_artisan_slug_craft_slug_practice_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artisan",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="craft",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="artisan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artisan",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="artisan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="craft",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="craft",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="location",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="craft",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
