# Generated by Django 6.1 on 2026-09-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_alter_artisan_options_alter_craft_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"ordering": ["ends_at"]},
        ),
        migrations.RenameField(
            model_name="auction",
            old_name="current_bid",
            new_name="current_price",
        ),
        migrations.RenameField(
            model_name="auction",
            old_name="end_time",
            new_name="ends_at",
        ),
        migrations.RenameField(
            model_name="practice",
            old_name="cultural_context",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="artisan",
            name="practices",
        ),
        migrations.RemoveField(
            model_name="artisan",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="artisan",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="craft",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="craft",
            name="process_video",
        ),
        migrations.RemoveField(
            model_name="craft",
            name="published",
        ),
        migrations.RemoveField(
            model_name="craft",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="practice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="practice",
            name="short_description",
        ),
        migrations.AddField(
            model_name="auction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="craft",
            name="minimum_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The minimum price the artisan is willing to accept.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="location",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name="craft",
            name="category",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="craft",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="craft",
            name="making_video",
            field=models.URLField(
                blank=True, help_text="YouTube or other process video link.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="craft",
            name="name",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="craft",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="craft",
            name="selling_method",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Price"),
                    ("offers", "Accept Offers"),
                    ("auction", "Auction"),
                ],
                default="fixed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="craft",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name="practice",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="practice",
            name="region",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="practice",
            name="slug",
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
